# Generated by Django 3.0.1 on 2020-03-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=5)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('Account', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('BDay', models.DateField()),
                ('Photo', models.URLField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
