# Generated by Django 3.0.1 on 2020-03-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
