# Generated by Django 3.0.4 on 2020-07-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Address',
        ),
    ]
