# Generated by Django 3.0.1 on 2020-05-02 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Ans',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='Ques',
            field=models.TextField(max_length=500),
        ),
    ]
