# Generated by Django 3.0.5 on 2020-04-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Ans',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Ques',
            field=models.TextField(max_length=500),
        ),
    ]
