# Generated by Django 3.0.1 on 2020-05-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200410_0742'),
        ('questions', '0004_auto_20200502_1701'),
    ]

    operations = [
    ]
