# Generated by Django 3.0.4 on 2020-06-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='q1',
            new_name='a1',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='q10',
            new_name='a10',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='q2',
            new_name='a2',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='q3',
            new_name='a3',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='q4',
            new_name='a4',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='q5',
            new_name='a5',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='q6',
            new_name='a6',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='q7',
            new_name='a7',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='q8',
            new_name='a8',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='q9',
            new_name='a9',
        ),
    ]
