# Generated by Django 3.0.1 on 2020-06-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_question'),
        ('questions', '0007_auto_20200627_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AlterField(
            model_name='answer',
            name='a1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Member'),
        ),
    ]
