# Generated by Django 3.0.1 on 2020-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20200628_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuesNum', models.CharField(max_length=10000)),
                ('Difficulties', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('Ques', models.TextField(max_length=500)),
                ('Ans', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
