# Generated by Django 3.0.4 on 2020-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20200628_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_engineer',
            name='QuesNum',
            field=models.IntegerField(),
        ),
    ]
