# Generated by Django 3.0.4 on 2020-07-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_investment_banking'),
        ('questions', '0011_auto_20200705_1620'),
    ]

    operations = [
    ]
