# Generated by Django 3.0.4 on 2020-07-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200707_1920'),
        ('questions', '0013_merge_20200705_1719'),
    ]

    operations = [
    ]
