# Generated by Django 3.0.4 on 2020-07-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a9',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
