# Generated by Django 3.0.4 on 2020-07-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_question'),
        ('questions', '0016_auto_20200712_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_a1', models.CharField(blank=True, max_length=500)),
                ('rec_r1', models.CharField(blank=True, max_length=500)),
                ('rec_a2', models.CharField(blank=True, max_length=500)),
                ('rec_r2', models.CharField(blank=True, max_length=500)),
                ('rec_a3', models.CharField(blank=True, max_length=500)),
                ('rec_r3', models.CharField(blank=True, max_length=500)),
                ('rec_a4', models.CharField(blank=True, max_length=500)),
                ('rec_r4', models.CharField(blank=True, max_length=500)),
                ('rec_a5', models.CharField(blank=True, max_length=500)),
                ('rec_r5', models.CharField(blank=True, max_length=500)),
                ('rec_a6', models.CharField(blank=True, max_length=500)),
                ('rec_r6', models.CharField(blank=True, max_length=500)),
                ('rec_a7', models.CharField(blank=True, max_length=500)),
                ('rec_r7', models.CharField(blank=True, max_length=500)),
                ('rec_a8', models.CharField(blank=True, max_length=500)),
                ('rec_r8', models.CharField(blank=True, max_length=500)),
                ('rec_a9', models.CharField(blank=True, max_length=500)),
                ('rec_r9', models.CharField(blank=True, max_length=500)),
                ('rec_a10', models.CharField(blank=True, max_length=500)),
                ('rec_r10', models.CharField(blank=True, max_length=500)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
            ],
        ),
    ]
