# Generated by Django 3.0.4 on 2020-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_answer_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(blank=True, max_length=100)),
                ('videodate', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='session_id',
        ),
    ]
