# Generated by Django 3.0.4 on 2020-07-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20200717_0049'),
        ('questions', '0018_video'),
    ]

    operations = [
    ]
