# Generated by Django 3.0.4 on 2020-07-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_member_address'),
        ('questions', '0020_merge_20200718_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member'),
        ),
        migrations.AlterField(
            model_name='result',
            name='userID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Member'),
            preserve_default=False,
        ),
    ]
