# Generated by Django 3.0.5 on 2020-07-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20200719_1017'),
        ('questions', '0021_auto_20200719_1807'),
    ]

    operations = [
    ]
