# Generated by Django 3.0.4 on 2020-07-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_auto_20200719_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Job_pls_dont_add_shit_into_this_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuesNum', models.IntegerField()),
                ('Difficulties', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('Ques', models.TextField(max_length=500)),
                ('Ans', models.TextField(max_length=800, null=True)),
            ],
        ),
    ]
