# Generated by Django 3.0.4 on 2020-07-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_test_job_pls_dont_add_shit_into_this_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_Job_pls_dont_add_shit_into_this_model',
            new_name='Test_Job_pls_dont_add_shit_into_this_model_thank',
        ),
    ]
