# Generated by Django 3.0.5 on 2020-08-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20200723_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='b1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b10',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b2',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b3',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b4',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b5',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b6',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b7',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b8',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='b9',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
