# Generated by Django 3.0.1 on 2020-08-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20200811_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
