# Generated by Django 3.0.1 on 2020-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20200827_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a1',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
