# Generated by Django 3.0.5 on 2020-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_auto_20200827_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuesNum', models.IntegerField()),
                ('Difficulties', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('Ques', models.TextField(max_length=500)),
                ('Ans', models.TextField(max_length=800, null=True)),
                ('Keywords', models.TextField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware_Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuesNum', models.IntegerField()),
                ('Difficulties', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('Ques', models.TextField(max_length=500)),
                ('Ans', models.TextField(max_length=800, null=True)),
                ('Keywords', models.TextField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuesNum', models.IntegerField()),
                ('Difficulties', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('Ques', models.TextField(max_length=500)),
                ('Ans', models.TextField(max_length=800, null=True)),
                ('Keywords', models.TextField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ML_Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuesNum', models.IntegerField()),
                ('Difficulties', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('Ques', models.TextField(max_length=500)),
                ('Ans', models.TextField(max_length=800, null=True)),
                ('Keywords', models.TextField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantitative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuesNum', models.IntegerField()),
                ('Difficulties', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('Ques', models.TextField(max_length=500)),
                ('Ans', models.TextField(max_length=800, null=True)),
                ('Keywords', models.TextField(max_length=800, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Database_Administrator',
        ),
        migrations.DeleteModel(
            name='Network_Engineer',
        ),
        migrations.DeleteModel(
            name='Quantitative_Trading',
        ),
        migrations.DeleteModel(
            name='System_Engineer',
        ),
        migrations.DeleteModel(
            name='Venture_Capital',
        ),
        migrations.AddField(
            model_name='data_scientist',
            name='Keywords',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='investment_banking',
            name='Keywords',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='Keywords',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='sales_trading',
            name='Keywords',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='software_engineer',
            name='Keywords',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
