# Generated by Django 3.0.5 on 2020-08-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_member_address'),
        ('questions', '0031_auto_20200830_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='v1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='v10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='v2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='v3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='v4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='v5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='v6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='v7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='v8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='v9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a10',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a8',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a9',
            field=models.TextField(blank=True),
        ),
    ]
