# Generated by Django 3.1 on 2020-08-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_auto_20200831_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videofile',
            new_name='vid1',
        ),
        migrations.AddField(
            model_name='video',
            name='vid10',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='vid2',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='vid3',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='vid4',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='vid5',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='vid6',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='vid7',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='vid8',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='vid9',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
