# Generated by Django 3.1 on 2020-08-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0033_auto_20200831_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_job',
            field=models.TextField(blank=True),
        ),
    ]
