# Generated by Django 3.0.5 on 2020-08-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0034_answer_selected_job'),
        ('questions', '0032_auto_20200830_2303'),
    ]

    operations = [
    ]
