# Generated by Django 3.1 on 2020-09-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_auto_20200906_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MIS',
            new_name='DBA',
        ),
        migrations.AddField(
            model_name='result',
            name='selected_job',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
