# Generated by Django 3.0.1 on 2020-09-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_auto_20200907_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='t1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='t10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='t2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='t3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='t4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='t5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='t6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='t7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='t8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='t9',
            field=models.TextField(blank=True),
        ),
    ]
