# Generated by Django 3.0.5 on 2020-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_auto_20200908_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='t1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='t9',
            field=models.TextField(blank=True),
        ),
    ]
