# Generated by Django 3.0.5 on 2020-09-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0039_auto_20200927_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='t1',
            new_name='time1',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='t10',
            new_name='time10',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='t2',
            new_name='time2',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='t3',
            new_name='time3',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='t4',
            new_name='time4',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='t5',
            new_name='time5',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='t6',
            new_name='time6',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='t7',
            new_name='time7',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='t8',
            new_name='time8',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='t9',
            new_name='time9',
        ),
    ]
