# Generated by Django 3.0.5 on 2020-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_auto_20200927_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time6',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time7',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time8',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time9',
            field=models.IntegerField(null=True),
        ),
    ]
