# Generated by Django 3.0.1 on 2020-10-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0042_auto_20200930_1607'),
        ('questions', '0042_auto_20200930_0639'),
    ]

    operations = [
    ]
